Fractal Image Compressor: MSaupePredictor::MSaupePredictor::OneRangePredictor Class Reference
MSaupePredictor::MSaupePredictor::OneRangePredictor Class Reference
Implementation of the one-range-predictor from IStdEncPredictor interface.
#include <saupePredictor.h>
Classes
struct HeapInfo
Struct representing one node of the KD-tree and its distance form the range block.
class SEnormalizator
A convertor from SE in regular space to SE in normalized space.
Public Member Functions
IOneRangePredictor interface
Predictions & getChunk (float maxPredictedSE, Predictions &store)
Makes several predictions at once, returns store reference.
~OneRangePredictor ()
Protected Member Functions
OneRangePredictor (const NewPredictorData &data, int chunkSize_, const Tree &tree, int maxPredicts)
Creates a new predictor for a range block (prepares tree-heaps, etc.
Protected Attributes
std::vector< PointHeap * > heaps
Pointers to the heaps for every rotation and inversion.
std::vector< HeapInfo > infoHeap
Heap built from heaps according to their best SEs.
KDReal * points
Normalized range rotations and inversions used by the heaps (owned).
int chunkSize
The suggested count for predicted ranges returned at once.
int predsRemain
Max. remaining count of predictions to be returned.
int heapCount
The number of heaps.
bool firstChunk
True if nothing has been predicted yet, false otherwise.
bool allowRotations
Like NewPredictorData::allowRotations.
bool isRegular
Indicates regularity of the range block (see RangeNode::isRegular).
Private Attributes
class
MSaupePredictor::OneRangePredictor::SEnormalizator errorNorm
A convertor from SE in regular space to SE in normalized space.
Friends
class MSaupePredictor
Detailed Description
Implementation of the one-range-predictor from IStdEncPredictor interface.
Definition at line 82 of file saupePredictor.h.
Constructor & Destructor Documentation
MSaupePredictor::MSaupePredictor::OneRangePredictor::OneRangePredictor (const NewPredictorData & data, int chunkSize_, const Tree & tree, int maxPredicts) [protected]
Creates a new predictor for a range block (prepares tree-heaps, etc.
)
Definition at line 227 of file saupePredictor.cpp.
References KDTree< T >::KDTree::PointHeap::getTopSE(), KDTree< T >::length, log2ceil(), MatrixSlice< T, I >::makeRaw(), MatrixSlice< T, I >::start, and FieldMath::transform2().
Member Data Documentation
class MSaupePredictor::OneRangePredictor::SEnormalizator MSaupePredictor::MSaupePredictor::OneRangePredictor::errorNorm [private]
A convertor from SE in regular space to SE in normalized space.
used to compute SE in the normalized space (from normal SE)
The documentation for this class was generated from the following files:
modules/saupePredictor.h
modules/saupePredictor.cpp